### ISSUE TITLE
The long rest button doesn't work and throws an error

### ISSUE THREAD

**Issue by Zamrod** [fantasycalendar/FoundryVTT-RestRecovery#15]
Module Version: 1.0.0

When I click the Long Rest button on a PC nothing happens and I get the following error:

```
helpers.mjs:293 
        
       Uncaught (in promise) TypeError: key.split is not a function or its return value is not iterable
[Detected 3 packages: rest-recovery, lib-wrapper, system:dnd5e]
    at Module.getProperty (common/utils/helpers.mjs:293:22)
    at Localization.localize (foundry.js:4604:27)
    at getSetting (modules/rest-recovery/dist/module.js:11084:34)
    at RestWorkflow.fetchFeatures (modules/rest-recovery/dist/module.js:12334:35)
    at new RestWorkflow (modules/rest-recovery/dist/module.js:12166:10)
    at Function.make (modules/rest-recovery/dist/module.js:12199:22)
    at Actor5e.🎁CONFIG.Actor.documentClass.prototype.longRest#rest-recovery (modules/rest-recovery/dist/module.js:14877:18)
    at Wrapper.🎁call_wrapper [as call_wrapper] (modules/lib-wrapper/lib-wrapper.js:1:36884)
    at Actor5e.🎁CONFIG.Actor.documentClass.prototype.longRest#0 (modules/lib-wrapper/lib-wrapper.js:1:32361)
    at ActorSheet5eCharacter._onLongRest (systems/dnd5e/module/actor/sheets/character.js:271:23)
```

**Comment by Haxxer** [comment]
I don't get this error - could you screenshot your settings so that I can try it on my end?

**Comment by Haxxer** [comment]
Found it! Releasing a patch. Thank you.
