### ISSUE TITLE
[BUG] Error in console log when spending hit dice in dnd5e 2.0.3

### ISSUE THREAD

**Issue by Zamrod** [fantasycalendar/FoundryVTT-RestRecovery#94]
**Describe the bug**
Rolling hitdice while short resting using dnd5e 2.0.3 gives an error and the bar doesn't change. But the hitpoints of the actor seems to:

```
foundry.js:747 TypeError: Cannot set properties of undefined (setting '0')
[Detected 2 packages: rest-recovery, system:dnd5e]
    at Object.fn (module.js:16397:16)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at Actor5e.rollHitDie (actor.mjs:1287:16)
    at RestWorkflow.rollHitDice (module.js:16639:35)
    at rollHitDice (module.js:18475:35)
    at HTMLButtonElement.click_handler (module.js:16214:5)
```

**Setup:**
 - Foundry Version: 10.286
 - System Version: dnd5e 2.0.3
 - Rest Recovery Version: 1.3.2
 - Browser & version: Electron built in

**Comment by Haxxer** [comment]
Fixed in 1.3.3
