### ISSUE TITLE
[BUG] Error on canvas load

### ISSUE THREAD

**Issue by Zamrod** [fantasycalendar/FoundryVTT-RestRecovery#95]
**Describe the bug**
The error comes up on canvas load.

```module.js:22354 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
[Detected 1 package: rest-recovery]
    at findOldSettingValue (module.js:22354:76)
    at migrate_1_3_3 (module.js:22362:62)
    at migrate (module.js:22350:9)
    at Object.fn (module.js:22380:3)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7854:11)
    at async Game._initializeGameView (foundry.js:8899:5)
    at async Game.initialize (foundry.js:7727:5)
```

**Setup:**
 - Foundry Version: 10.286
 - System Version: dnd5e 2.0.3
 - Rest Recovery Version: 1.3.2
 - Browser & version Electron built in browser

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by Haxxer** [comment]
Fixed in 1.3.3
